Repository asdf-community/asdf-direnv, pull requests merged in 2019-11, with the labels that each got.

#9 Add tips for direnv beginners
  README.md
Labels: documentation

#11 Removes dead shims (#10)
  README.md
  shims/direnv_use_asdf
Labels: documentation, enhancement

#14 New feature `use asdf current` to activate current plugins.
  .github/workflows/workflow.yml
  README.md
  shims/direnv_use_asdf
  test/test_helpers.bash
  test/use_asdf.bats
Labels: enhancement

#16 Use `direnv dump` instead of `direnv dotenv`
  bin/direnv_use_asdf
  shims/direnv_use_asdf
  test/use_asdf.bats
Labels: bug

#26 Move info about direnv_use_asdf to .direnvrc section
  README.md
Labels: documentation
